boutique/urls.py
from django.views.generic import TemplateView
from django.conf.urls import url
from django.urls import path
from . import views


app_name = 'boutique'

urlpatterns = [
    url(r'^$', views.accueil, name='accueil'),
    url(r'^boutique$', views.Boutique, name='boutique'),
    path('boutique/produit/<int:pk>-<str:slug>/', views.DetailProduit.as_view(), name='details'),
    url(r'^souscategorie/(?P<id_sous_categorie>\d+)$', views.produit_du_sous_categorie, name='sous_categorie_produit'),
    url(r'^categorie/(?P<id_categorie>\d+)/(?P<id_sous_categorie>\d+)$',views.produit_dans_categorie, name="categorie_liste_produit"),
    url(r'^recherche/$', views.recherche, name='recherche'),
    url(r"inscription/", views.inscription, name='inscription'),
    url(r'^connexion/$', views.connexion , name='connexion'),
    url(r'^deconnexion/$', views.deconnexion, name='deconnexion'),
    url(r'^passwordchange/$', views.changer_mot_de_passe, name='passwordchange'),
    url(r'^profil/$', views.profil, name='profil'),
    url(r'^profil/modifprofil/$', views.modif_profil, name='modif_profil'),
    url(r'^produit/achat/(?P<id_produit>\d+)/$', views.acheter, name='achat'),
    url(r'^ajout-au-panier/$', views.ajout_au_panier, name='ajout_au_panier'),
    path('sup-item-paier/<int:pk>/', views.sup_item_panier, name='supprimer'),
    url(r'^commandevalider/$', TemplateView.as_view(template_name='boutique/merci.html'), name="merci"),
    url(r'^Valider/$', TemplateView.as_view(template_name='boutique/aurevoir.html'), name="aurevoir"),
    url(r'^validercaisse/$', views.lacaisse , name='caisse'),
    url(r'^sinalbug/$', views.signal_bug, name='bug'),
    url(r'^contact/$', views.contacter, name="contacter"),
]

ecom/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path, include
from . import settings
from boutique.views import accueil, ajout_au_panier
import os

urlpatterns = [
    path('', accueil),
    path('medard/admin/', admin.site.urls),
    url(r'ckeditor/', include('ckeditor_uploader.urls')),
    path('ajout_au_panier/', ajout_au_panier, name='ajout_au_panier'),
    path('boutique/', include('boutique.urls', namespace='boutique')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns=[
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

boutique/views.py
from django.shortcuts import render, get_object_or_404, Http404, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.urls import reverse, NoReverseMatch, resolve, Resolver404
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.debug import sensitive_variables
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.db import transaction, IntegrityError
from django.contrib.auth.models import User
from django.utils.html import strip_tags
from django.contrib import messages
from django.conf import settings
from django.db.models import Q
from datetime import datetime

# exception
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist

# Import de model
from .models import (Categorie, Produit, SousCategorie,
                    CompteUser, Contact, Panier, Bug, 
                    AvisDemande, Commande, PanierItem)

# import des formulaires
from .forms import (CompteUserForm, ConnexionForm, NewsletterForm, 
                    ParagraphErrorList, PasswordChangeForm, ProfilForm,
                    BugForm, ContactUsForm, PayementForm)


# Views

# Email
def envoie_mail(request, email, sujet, context):
    template = render_to_string('boutique/email_form1.html', context)
    email = EmailMultiAlternatives(
        sujet,
        template,
        settings.EMAIL_HOST_USER,
        [f'{email}']
        )
    email.attach_alternative(template, "text/html")
    email.send(fail_silently=False)

# Stock dans la boutique avec pagination
def Boutique(request):
    template_name = 'boutique/tous_produits.html'
    liste_produits = Produit.objects.filter(disponible=True).order_by('-date_de_creation')
    paginator = Paginator(liste_produits, 6, orphans=3)
    page = request.GET.get('page')

    try:
        liste_produits = paginator.page(page)
    except PageNotAnInteger:
        liste_produits = paginator.page(1)
    except EmptyPage:
        liste_produits = paginator.page(paginator.num_pages)

    resultat = len(liste_produits)
    return render(request,template_name, locals())

# liste des produits dans chaque sous categorie
def produit_du_sous_categorie(request, id_sous_categorie):

    try:
        id = id_sous_categorie
        liste_produits = get_object_or_404(SousCategorie, pk=id).produit_set.all().order_by('-date_de_creation')
    except:
        return Http404

    paginator = Paginator(liste_produits, 6, orphans=2)
    page = request.GET.get('page')

    try:
        liste_produits = paginator.page(page)
    except PageNotAnInteger:
        liste_produits = paginator.page(1)
    except EmptyPage:
        liste_produits = paginator.page(paginator.num_pages)

    return render(request, 'boutique/produit_sous_categorie.html', locals())

# Liste produits dans chaque categorie croisé avec sous categorie
def produit_dans_categorie(request, id_categorie, id_sous_categorie):

    try:
        id_categorie = id_categorie
        id_sous_categorie = id_sous_categorie

        #requete Q(pour chaque categorie et sous categorie on obtient la liste des produits)
        liste_produits = Produit.objects.filter(
            Q(categorie=get_object_or_404(Categorie, id=id_categorie)) & 
            Q(sous_categorie=get_object_or_404(SousCategorie, id=id_sous_categorie))
            ).order_by('-date_de_creation')
    except ValueError:
        return Http404

    paginator = Paginator(liste_produits, 6, orphans=3)
    page = request.GET.get('page')

    try:
        liste_produits = paginator.page(page)
    except PageNotAnInteger:
        liste_produits = paginator.page(1)
    except EmptyPage:
        liste_produits = paginator.page(paginator.num_pages)

    resultat = len(liste_produits)
    return render(request, 'boutique/produit_categorie.html', locals())

# Detail du prduit
class DetailProduit(DetailView):
    model = Produit
    context_object_name = 'un_produit'
    template_name = 'boutique/detail.html'
    
    def get_object(self):
        un_produit = super(DetailProduit, self).get_object()
        un_produit.etoile +=1
        un_produit.save()
        return un_produit

# Accueil
@sensitive_variables('email', 'contact')
def accueil(request):
    """
    liste des 12 produits les plus recents
    """
    liste_produits = Produit.objects.filter(
        disponible=True).order_by('-date_de_creation')[:12]
    liste_produits_promo = Produit.objects.filter(
        disponible=True,
        promotion=True).order_by('-date_de_creation')

    if request.method == "POST":
        envoi = False
        form = NewsletterForm(request.POST, error_class=ParagraphErrorList)
        if form.is_valid():
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            envoi = True

            try:
                with transaction.atomic():
                    contact = Contact.objects.filter(email=email)
                    if not contact.exists():
                        contact = Contact.objects.create(
                            prenom=last_name, 
                            email=email)
                        contact.save()
                    else:
                        contact.first()
                    messages.info(request, "Vous êtes maintenant inscrit aux nouvelles de soma électronic")
            except IntegrityError:
                form.errors['internal'] = "Une erreur interne est apparue. Merci de récommencer."
        
        else:
            errors = form.errors.items()
            messages.warning(request, "Une erreur est arrivée, veillez récommencer !")
       
        if envoi==True:
            try:
                envoie_mail(request, email, 'Inscription au Newsletter', context=locals())
            except:
                pass

    else:
        form = NewsletterForm()

    resultat = len(liste_produits)      
    return render(request, 'boutique/index.html', locals())

# Traitement de recherche
def recherche(request):
    query = request.GET.get('query')

    try:
        if not query:
            messages.info(request, "Veillez écrire le nom d'un produit pour la recherche.")
            liste_produits = Produit.objects.all()
        else:
            liste_produits = Produit.objects.filter(nom__icontains=query)
        if not liste_produits.exists():
            liste_produits = Produit.objects.filter(sous_categorie__nom__icontains=query)
        if not liste_produits.exists():
            liste_produits = Produit.objects.filter(categorie__nom__icontains=query)
    except IntegrityError:
        liste_produits = []

    resultat = len(liste_produits)
    return render(request, 'boutique/recherche.html', locals())

# traitement d'inscription
@sensitive_variables('username','email','password','user','profil')
def inscription(request):
    form = CompteUserForm(request.POST or None, error_class=ParagraphErrorList)
    
    if form.is_valid():
        username = form.cleaned_data['username']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        envoi = True

        try:
            with transaction.atomic():
                user = User.objects.create_user(username=username, 
                                    email=email, 
                                    password=password,
                                    )
                user.first_name = first_name
                user.last_name = last_name
                user.save()
                profil = CompteUser(user=user)
                profil.save()
                user = authenticate(username=username, password=password)
                
                if user:
                    login(request, user)
                    messages.add_message(request, messages.INFO, "Vous êtes connecté!")
                    return redirect('boutique:accueil')
        except IntegrityError:
            messages.warning(request, "Une erreur est arrivée, veillez récommencer!")
            return redirect('boutique:accueil')
    
    return render(request, 'boutique/inscription.html', locals())

# La connexion
@sensitive_variables('username', 'password', 'user')
def connexion(request):
    error = False

    if request.method == "POST":
        form = ConnexionForm(request.POST, error_class=ParagraphErrorList)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password) 
            if user:
                login(request, user)
                redirection = request.GET.get('next')

                if redirection:
                    return redirect(reverse(redirection))
                else:
                    return redirect('boutique:accueil')
            else:
                error = True
    else:
        form = ConnexionForm()
    return render(request, 'boutique/connexion.html', locals())

# La deconnexion
@sensitive_post_parameters('user','password')
def deconnexion(request):
    logout(request)
    messages.success(request, "vous êtes maintenant déconnecté !")
    return redirect("boutique:accueil")

# Gestion du profil
@login_required(login_url='boutique:connexion')
def profil(request):
    profil = get_object_or_404(CompteUser, user=request.user)
    try:
        liste_panier = Panier.objects.filter(user=CompteUser.objects.get(user=request.user),traite=True)
    except:
        liste_panier = []
    return render(request, 'boutique/profil.html', locals())

# Modification du compte
@login_required(login_url='boutique:connexion')
def modif_profil(request):

boutique/templates/boutique/categorie.html
<ul class="navbar-nav ">
    {% for cat in liste_categories %}                
    <li class="nav-item dropdown mx-3">
        <a href="" class="nav-link ml-n3 dropdown-toggle text-white lien-categorie" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ cat.nom }}</a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            {% for sous_cat in cat.souscategorie.all %}
            <a href="{% url 'boutique:categorie_liste_produit' id_categorie=cat.id id_sous_categorie=sous_cat.id %}" class="dropdown-item">{{ sous_cat }}</a>
            {% endfor %}
        </div>
    </li>
    {% endfor %}
</ul>

boutique/templates/boutique/changemdp.html
{% extends 'boutique/connexion.html' %}
{% block title %}changement de mot de passe{% endblock %}
{% block content %}
<div class="d-flex my-5">
    <div class="formulare mx-auto">
        <h5>Modification du mot de passe:</h5>
        <hr>
        {% if error %}
            <p style="color: rgb(236, 24, 24);"><strong>Ancien mot de passe incorret</strong></p>
        {% endif %}
        <form action="{% url 'boutique:passwordchange' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Modifier</button>
        </form>
        <hr>
        <div class="d-inline-flex flex-wrap">
            <a href="{% url 'boutique:inscription' %}">créer un autre compte.</a>
        </div>
    </div>
</div>
{% endblock %}

boutique/templates/boutique/contacter.html
{% extends 'boutique/inscription.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="d-block mx-auto my-4">
            <h5 class="mb-3">Contactez nous en remplissant ce formulaire</h5>
            <form action="{% url 'boutique:contacter' %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Envoyer</button>
            </form>
            <p class="text-right">Retour à la boutique <a href="{% url 'boutique:boutique' %}">ici !</a></p>
        </div>
    </div>
   
</div>
{% endblock %}

boutique/templates/boutique/contenu_panier.html
<div class="d-table mx-auto">
    <h4>Contenu du Panier.</h4>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    <svg height="1.5rem" viewBox="0 0 448 448.55357" width="1.5rem" xmlns="http://www.w3.org/2000/svg"><path d="m224.550781 0c-123.667969 0-224.273437 100.605469-224.273437 224.277344 0 123.667968 100.605468 224.277344 224.273437 224.277344 123.664063 0 224.269531-100.609376 224.269531-224.277344 0-123.671875-100.605468-224.277344-224.269531-224.277344zm0 430.269531c-113.582031 0-205.988281-92.414062-205.988281-205.992187 0-113.582032 92.40625-205.992188 205.988281-205.992188 113.578125 0 205.984375 92.410156 205.984375 205.992188 0 113.578125-92.40625 205.992187-205.984375 205.992187zm0 0"/><path d="m340.378906 134.847656-159.46875 159.464844-72.191406-72.1875c-3.570312-3.570312-9.355469-3.570312-12.929688 0-3.570312 3.570312-3.570312 9.355469 0 12.929688l78.65625 78.652343c1.785157 1.785157 4.125 2.675781 6.464844 2.675781s4.679688-.890624 6.464844-2.675781l165.933594-165.929687c3.570312-3.570313 3.570312-9.359375 0-12.929688-3.570313-3.570312-9.359375-3.570312-12.929688 0zm0 0"/></svg>
                    
                </th>
                <th scope="col">Capture</th>
                <th scope="col">Produits</th>
                <th scope="col">Quantité</th>
                <th scope="col">Prix total</th>
            </tr>
        </thead>
        <tbody>
            {% for produit in panierproduit %}
            <tr>
                <th scope="row">
                    <a href="{% url 'boutique:supprimer' pk=produit.produits.id %}">
                        <svg height="1rem" viewBox="0 0 365.71733 365" width="1rem" xmlns="http://www.w3.org/2000/svg"><g fill="#f44336"><path d="m356.339844 296.347656-286.613282-286.613281c-12.5-12.5-32.765624-12.5-45.246093 0l-15.105469 15.082031c-12.5 12.503906-12.5 32.769532 0 45.25l286.613281 286.613282c12.503907 12.5 32.769531 12.5 45.25 0l15.082031-15.082032c12.523438-12.480468 12.523438-32.75.019532-45.25zm0 0"/><path d="m295.988281 9.734375-286.613281 286.613281c-12.5 12.5-12.5 32.769532 0 45.25l15.082031 15.082032c12.503907 12.5 32.769531 12.5 45.25 0l286.632813-286.59375c12.503906-12.5 12.503906-32.765626 0-45.246094l-15.082032-15.082032c-12.5-12.523437-32.765624-12.523437-45.269531-.023437zm0 0"/></g></svg></th>
                    </a>
                <th><img src="{{produit.produits.image.url}}" width="25px" height="25px" alt="{{produit.nom}}"></th>
                <th class="font-weight-light">{{ produit.produits.nom }}</th>
                <th class="text-center">{{produit.quantite_du_produit }}</th>
                <th style="color: orange;">{{produit.prix_du_produit|floatformat }} <span class="font-weight-normal">{{ devise }}</span></th>
            </tr>
            {% empty %}
            <p>Panier Vide !</p>
            {% endfor %}
        </tbody>
    </table>
    <table class="table table-bordered">
        <tbody>
            <tr>
                <th scope="col">Total</th>
                <th style="color: #ed6b5b ;">{{ prix_total }} {{devise}}</th>
            </tr>
        </tbody>
    </table>
</div>

boutique/templates/boutique/index.html
{% extends 'boutique/base.html' %}

{% block title %}Accueil{% endblock %}

{% block newsletter %}
     {% include 'boutique/newsletter.html' %}                   
{% endblock %}

{%block search%}
    {% include 'boutique/recherche_form.html' %}
{%endblock%}

{% block cat %}
    {% include 'boutique/categorie.html' %}
{% endblock %}

    {% block souscategorie %}
        {% include 'boutique/sous_produit.html' %}
    {% endblock %}

    {% block carousel %}
        {% include 'boutique/promo.html' %}
    {% endblock %}

    {% block produit %}
        {% include 'boutique/liste.html' %}
    {% endblock %}

    {% block plus-de-produit %}
    <div class="plus-de-produit d-inline-flex  align-items-center">
        <a href="{% url 'boutique:boutique' %}">
            <div class="spinner-grow text-primary" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </a>
        <a href="{% url 'boutique:boutique' %}">Tous les produits</a>
    </div>
    {% endblock%}
              

boutique/templates/boutique/modif_profil.html
{% extends 'boutique/connexion.html' %}
{% block title %}Modification du profil{% endblock %}
{% block content %}
<div class="d-flex my-5">
    <div class="formulare mx-auto w-50">
        <h3 class="text-center">Modification du compte</h3>
        <hr>
        <form action="{% url 'boutique:modif_profil' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Enregistrer</button>
        </form>
    </div>
</div>
{% endblock %}

boutique/templates/boutique/panier.html
{% extends 'boutique/index.html' %}
{% block title %}SE Ajout au panier{% endblock %}

{% block content%}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'boutique:accueil' %}">Accueil</a></li>
      <li class="breadcrumb-item"><a href="{% url 'boutique:boutique' %}">Produit</a></li>
      <li class="breadcrumb-item active" aria-current="page">Panier</li>
    </ol>
</nav>
<div class="d-table mx-auto">
    {% for message in messages%}
    <div class="alert alert-warning alert-dismissible fade show mr-3" role="alert">
        <strong>Info!</strong> {{message}}.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
   
  {% include 'boutique/contenu_panier.html' %}
  <div class="d-flex"> 
      <a href="{% url 'boutique:boutique' %}" class="btn btn-outline-danger ">Poursuivre les achats!</a>
      <a href="{% url 'boutique:caisse' %}" class="btn btn-outline-danger ml-auto">Direction à la caisse</a>
  </div>
  <div style="height: 30px;">
  </div>
</div>
{% endblock %}

boutique/templates/boutique/produit_categorie.html
{% extends 'boutique/index.html' %}
{% block title %}SE-Categorie{% endblock %}

{% block salut%}
{% endblock%}

{% block carousel %}
{% endblock %}
{% block produit %}
        {% include 'boutique/liste.html' %}
{% endblock %}
{% block plus-de-produit %}
{% endblock %}

boutique/templates/boutique/profil.html
{% extends 'boutique/connexion.html' %}
{% block title %}Profil{% endblock %}
{% load humanize %}
{% block content %}
<div class="profil mt-2">
    <div class="row">
        <div class="col-12 col-md-6">
            <h2 class="mb-n1">Mon Profil</h2>
            <a href="{% url 'boutique:deconnexion' %}" class="ml-2">déconnexion</a>
            <hr>
            <div>
                <h6>Nom d'utilisateur : {{ user.username }}</h6>
                <h6>Nom : {{ user.first_name }}</h6>
                <h6>Prénom : {{ user.last_name }}</h6>
                <p>Email : {{ user.email }}</p>
                <hr>
                <h6 >Informations supplémentaires:</h6>
                <p>Bio: {% if profil.bio %} {{ profil.bio }} {% else %} Vide {% endif %}</p>
                <p>Inscrit au newsletter: {% if profil.inscrit_newsletter %} Oui {% else %} Non {% endif %}</p>
                <p>Dernière connexion : {{ user.last_login|naturaltime }}</p>
                <p>Date d'inscription: {{ user.date_joined|naturalday }}</p>
                <a href="{% url 'boutique:passwordchange' %}" class="btn btn-outline-primary">Changer le mot de passe</a>
                <hr>
            </div>
        </div>
        <div class="col-12 col-md-6 text-left text-md-right">
            <a href="{% url 'boutique:modif_profil' %}" class="btn btn-primary btn-sm">Modifier le profil</a>
        </div>
    </div>
    <div class="row mt-3">
        <h4 class="ml-3">Mes Paniers</h4>
        <hr>
    </div>
    <div class="row">
        <div class="col-12 col-lg-4">
          <div class="list-group" id="list-tab" role="tablist">
            {% for panier in liste_panier %}
            {% if forloop.first %}
            <a class="list-group-item list-group-item-action active" id="list-{{panier.nom}}-list" data-toggle="list" href="#{{ panier.nom }}" role="tab" aria-controls="home">{{ panier.nom|truncatewords:20 }}</a>
            {% else %}
            <a class="list-group-item list-group-item-action" id="list-{{panier.nom}}-list" data-toggle="list" href="#{{ panier.nom }}" role="tab" aria-controls="profile">{{ panier.nom|truncatewords:20 }} </a>
            {% endif %}
            {% empty %}
            <p>Pas de panier à ce jour!</p>
            {%endfor%}
          </div>
        </div>
        <div class="col-12 col-lg-8">
          <div class="tab-content" id="nav-tabContent">
            {% for panier in liste_panier %}
            <div class="tab-pane fade show active" id="{{ panier.nom }}" role="tabpanel" aria-labelledby="list-{{panier.nom}}-list">
              <table class="table table-bordered">
                {% for prod in panier.produits.all %}
                <tr>
                  <th><img src="{{prod.produits.image.url}}" width="25px" height="25px" alt="{{produit.nom}}"></th>
                  <th class="font-weight-light">{{ prod.produits.nom }}</th>
                  <th class="text-center">{{prod.quantite_du_produit }}</th>
                  <th style="color: orange;">{{prod.prix_du_produit|floatformat }} <span class="font-weight-normal">{{ devise }}</span></th>
                </tr>
                {% endfor %}
              </table>
            </div>
            {% endfor %}
            
          </div>
        </div>
      </div>
</div>
{% endblock %}

boutique/templates/boutique/recherche_form.html
<form class="my-md-2 my-lg-0 d-inline-flex align-items-center mr-2 mr-md-0"   action="{% url 'boutique:recherche' %}" method="GET" accept-charset="utf-8" >
    <input class="form-control" type="search" placeholder="Entrer un produit" aria-label="Search" name="query" style="width: 12rem;">
    <button class="btn btn-outline-primary my-2 my-sm-0 ml-2" type="submit">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
            <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
        </svg>
    </button>
</form>

boutique/templates/boutique/sous_produit.html
{% for sous_cat in liste_sous_categories %}
    <a style="width: 12.2rem;" class="list-group-item" href="{% url 'boutique:sous_categorie_produit' id_sous_categorie=sous_cat.id %}">{{sous_cat}}</a>
{% endfor %}
<!-- {% block prod%}
    {% include 'boutique/liste.html' %}
{% endblock%} -->

boutique/templates/boutique/tous_produits.html
{% extends 'boutique/index.html' %}
{% block title %}somae-boutique-produits{% endblock %}
{% block carousel %}
{% endblock %}
{% block produit %}
        {% include 'boutique/liste.html' %}
{% endblock %}
{% block plus-de-produit %}

{% endblock %}